### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by benbahrenburg** [chanricle/CKTextView#12]
Is a great project. Any thoughts on updating to provide Swift 3 support?

**Comment by tuesleep** [comment]
Of course when Swift 3 stable released.

**Comment by benbahrenburg** [comment]
@chanricle thanks for all of the help. Is there a timing for updating to Swift 3?  I did a quick upgrade and most of it upgrades cleanly. There a several problems with the UITextViewDelegate extension.

**Comment by tuesleep** [comment]
@benbahrenburg Swift 3.0 was supported. The tag 0.5.0 is it. 
But Cocoapod trunk push fail at time.

**Comment by benbahrenburg** [comment]
@chanricle thank you.

**Comment by chanricle** [comment]
Cocoapod tag 0.5.0 is available.
