### ISSUE TITLE
Swift 3.2 or Swift 4.0 Support

### ISSUE THREAD

**Issue by benbahrenburg** [chanricle/CKTextView#18]
Hello, 
Are there any plans to support Swift 3.2 or Swift 4.0?  I did a quick test upgrade and found the changes to NSAttributedString seems to have an impact.  Have you or anyone else had any luck upgrading?

**Comment by tuesleep** [comment]
Branch `master` and `develop` is migrated to Swift 4.

**Comment by benbahrenburg** [comment]
Awesome thank you.
