### ISSUE TITLE
Where is Italic ?

### ISSUE THREAD

**Issue by ljs19923** [chanricle/CKTextView#27]
Hi! I dont see Italic... Do you know why ?
![image](https://user-images.githubusercontent.com/5727223/40516196-b60dfade-5f7d-11e8-9c72-9b6e020888c1.png)
![image](https://user-images.githubusercontent.com/5727223/40516201-b8417574-5f7d-11e8-9fe9-28ed68f8b2c1.png)

**Comment by tuesleep** [comment]
Italic format menu will showing after "Select Text".
